COUNTRY_DATA = {
    "US": {
        "states":   [
            "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
            "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
            "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
            "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
            "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
            "New Hampshire", "New Jersey", "New Mexico", "New York",
            "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
            "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
            "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
            "West Virginia", "Wisconsin", "Wyoming",
        ],
        "networks": ["ATT", "Verizon", "T-Mobile", "Sprint", "Comcast", "Charter", "CenturyLink", "Cox"],
        "cities": {
            "Alabama":        ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
            "Alaska":         ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
            "Arizona":        ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale", "Tempe"],
            "Arkansas":       ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
            "California":     ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland"],
            "Colorado":       ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Boulder"],
            "Connecticut":    ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
            "Delaware":       ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
            "Florida":        ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Tallahassee", "Fort Lauderdale"],
            "Georgia":        ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens"],
            "Hawaii":         ["Honolulu", "Hilo", "Kailua", "Pearl City", "Waipahu"],
            "Idaho":          ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
            "Illinois":       ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Springfield"],
            "Indiana":        ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
            "Iowa":           ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
            "Kansas":         ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka"],
            "Kentucky":       ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
            "Louisiana":      ["New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette"],
            "Maine":          ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
            "Maryland":       ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie"],
            "Massachusetts":  ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
            "Michigan":       ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor"],
            "Minnesota":      ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
            "Mississippi":    ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
            "Missouri":       ["Kansas City", "Saint Louis", "Springfield", "Columbia", "Independence"],
            "Montana":        ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
            "Nebraska":       ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
            "Nevada":         ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
            "New Hampshire":  ["Manchester", "Nashua", "Concord", "Dover", "Rochester"],
            "New Jersey":     ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"],
            "New Mexico":     ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
            "New York":       ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
            "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
            "North Dakota":   ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
            "Ohio":           ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
            "Oklahoma":       ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
            "Oregon":         ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro"],
            "Pennsylvania":   ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
            "Rhode Island":   ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"],
            "South Carolina": ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Greenville"],
            "South Dakota":   ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
            "Tennessee":      ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
            "Texas":          ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington"],
            "Utah":           ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"],
            "Vermont":        ["Burlington", "South Burlington", "Rutland", "Barre", "Montpelier"],
            "Virginia":       ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News"],
            "Washington":     ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
            "West Virginia":  ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
            "Wisconsin":      ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
            "Wyoming":        ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
        },
    },
    "AU": {
        "states":   [
            "New South Wales", "Victoria", "Queensland", "South Australia",
            "Western Australia", "Tasmania", "Northern Territory",
            "Australian Capital Territory",
        ],
        "networks": ["Vodafone", "Telstra", "Optus", "TPG", "Aussie Broadband"],
        "cities": {
            "New South Wales":           ["Sydney", "Newcastle", "Wollongong", "Central Coast", "Maitland"],
            "Victoria":                  ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton"],
            "Queensland":                ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns"],
            "South Australia":           ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge", "Port Augusta"],
            "Western Australia":         ["Perth", "Bunbury", "Geraldton", "Kalgoorlie", "Albany"],
            "Tasmania":                  ["Hobart", "Launceston", "Devonport", "Burnie", "Queenstown"],
            "Northern Territory":        ["Darwin", "Alice Springs", "Palmerston", "Katherine", "Nhulunbuy"],
            "Australian Capital Territory": ["Canberra", "Belconnen", "Tuggeranong", "Gungahlin", "Woden"],
        },
    },
    "CA": {
        "states":   [
            "Alberta", "British Columbia", "Manitoba", "New Brunswick",
            "Newfoundland and Labrador", "Nova Scotia", "Northwest Territories",
            "Nunavut", "Ontario", "Prince Edward Island", "Quebec",
            "Saskatchewan", "Yukon",
        ],
        "networks": ["Rogers", "Bell", "Telus", "Freedom Mobile", "Shaw", "Videotron"],
        "cities": {
            "Alberta":                  ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "St. Albert"],
            "British Columbia":          ["Vancouver", "Surrey", "Burnaby", "Richmond", "Kelowna", "Abbotsford"],
            "Manitoba":                  ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"],
            "New Brunswick":             ["Moncton", "Saint John", "Fredericton", "Miramichi", "Edmundston"],
            "Newfoundland and Labrador": ["St. John's", "Corner Brook", "Gander", "Grand Falls-Windsor"],
            "Nova Scotia":               ["Halifax", "Dartmouth", "Sydney", "Truro", "New Glasgow"],
            "Northwest Territories":     ["Yellowknife", "Hay River", "Inuvik", "Fort Smith"],
            "Nunavut":                   ["Iqaluit", "Rankin Inlet", "Arviat", "Baker Lake"],
            "Ontario":                   ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London"],
            "Prince Edward Island":      ["Charlottetown", "Summerside", "Stratford", "Cornwall"],
            "Quebec":                    ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"],
            "Saskatchewan":              ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current"],
            "Yukon":                     ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction"],
        },
    },
    "GB": {
        "states":   ["England", "Scotland", "Wales", "Northern Ireland"],
        "networks": ["BT", "EE", "O2", "Vodafone", "Three", "Sky", "Virgin Media"],
        "cities": {
            "England":          ["London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Sheffield", "Bristol", "Leicester"],
            "Scotland":         ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness", "Stirling"],
            "Wales":            ["Cardiff", "Swansea", "Newport", "Bangor", "Wrexham"],
            "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry", "Armagh"],
        },
    },
    "DE": {
        "states":   [
            "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse",
            "Mecklenburg-Vorpommern", "Lower Saxony", "North Rhine-Westphalia",
            "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt",
            "Schleswig-Holstein", "Thuringia",
        ],
        "networks": ["Deutsche Telekom", "Vodafone", "O2", "1&1", "Freenet"],
        "cities": {
            "Bavaria":                ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Ingolstadt"],
            "Berlin":                 ["Berlin"],
            "Brandenburg":            ["Potsdam", "Cottbus", "Brandenburg an der Havel", "Frankfurt (Oder)"],
            "Bremen":                 ["Bremen", "Bremerhaven"],
            "Hamburg":                ["Hamburg"],
            "Hesse":                  ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"],
            "Mecklenburg-Vorpommern": ["Rostock", "Schwerin", "Neubrandenburg", "Stralsund"],
            "Lower Saxony":           ["Hanover", "Braunschweig", "Osnabrück", "Oldenburg"],
            "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg", "Bochum"],
            "Rhineland-Palatinate":   ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern"],
            "Saarland":               ["Saarbrücken", "Neunkirchen", "Homburg", "Saarlouis"],
            "Saxony":                 ["Dresden", "Leipzig", "Chemnitz", "Zwickau", "Erfurt"],
            "Saxony-Anhalt":          ["Magdeburg", "Halle", "Dessau-Roßlau", "Lutherstadt Wittenberg"],
            "Schleswig-Holstein":     ["Kiel", "Lübeck", "Flensburg", "Neumünster"],
            "Thuringia":              ["Erfurt", "Jena", "Gera", "Weimar", "Gotha"],
        },
    },
    "FR": {
        "states":   [
            "Ile-de-France", "Auvergne-Rhone-Alpes", "Bourgogne-Franche-Comte",
            "Bretagne", "Centre-Val de Loire", "Grand Est",
            "Hauts-de-France", "Normandie", "Nouvelle-Aquitaine",
            "Occitanie", "Pays de la Loire", "Provence-Alpes-Cote d'Azur",
        ],
        "networks": ["Orange", "SFR", "Bouygues Telecom", "Free Mobile"],
        "cities": {
            "Ile-de-France":              ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Versailles"],
            "Auvergne-Rhone-Alpes":       ["Lyon", "Grenoble", "Saint-Etienne", "Clermont-Ferrand", "Annecy"],
            "Bourgogne-Franche-Comte":    ["Dijon", "Besançon", "Chalon-sur-Saône", "Mâcon", "Auxerre"],
            "Bretagne":                   ["Rennes", "Brest", "Quimper", "Lorient", "Vannes"],
            "Centre-Val de Loire":        ["Tours", "Orléans", "Bourges", "Blois", "Chartres"],
            "Grand Est":                  ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"],
            "Hauts-de-France":            ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkirk"],
            "Normandie":                  ["Rouen", "Caen", "Le Havre", "Cherbourg", "Alençon"],
            "Nouvelle-Aquitaine":         ["Bordeaux", "Limoges", "Pau", "Bayonne", "La Rochelle"],
            "Occitanie":                  ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Narbonne"],
            "Pays de la Loire":           ["Nantes", "Le Mans", "Angers", "Saint-Nazaire", "Laval"],
            "Provence-Alpes-Cote d'Azur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon"],
        },
    },
    "JP": {
        "states":   ["Tokyo", "Osaka", "Kyoto", "Aichi", "Fukuoka", "Hokkaido", "Kanagawa", "Okinawa"],
        "networks": ["NTT", "SoftBank", "KDDI", "Rakuten Mobile"],
        "cities": {
            "Tokyo":    ["Shinjuku", "Shibuya", "Chiyoda", "Minato", "Setagaya", "Hachioji"],
            "Osaka":    ["Osaka", "Sakai", "Higashiosaka", "Hirakata", "Toyonaka"],
            "Kyoto":    ["Kyoto", "Uji", "Kameoka", "Maizuru", "Fukuchiyama"],
            "Aichi":    ["Nagoya", "Toyota", "Okazaki", "Ichinomiya", "Toyohashi"],
            "Fukuoka":  ["Fukuoka", "Kitakyushu", "Kurume", "Omuta", "Iizuka"],
            "Hokkaido": ["Sapporo", "Asahikawa", "Hakodate", "Kushiro", "Tomakomai"],
            "Kanagawa": ["Yokohama", "Kawasaki", "Sagamihara", "Fujisawa", "Yokosuka"],
            "Okinawa":  ["Naha", "Okinawa City", "Uruma", "Ginowan", "Urasoe"],
        },
    },
    "SG": {
        "states":   ["Central", "North", "South", "East", "West"],
        "networks": ["Singtel", "StarHub", "M1", "TPG Telecom"],
        "cities": {
            "Central": ["Orchard", "Marina Bay", "Toa Payoh", "Bishan", "Ang Mo Kio"],
            "North":   ["Woodlands", "Yishun", "Sembawang", "Canberra"],
            "South":   ["Buona Vista", "Queenstown", "Telok Blangah", "Harbourfront"],
            "East":    ["Tampines", "Bedok", "Pasir Ris", "Changi", "Geylang"],
            "West":    ["Jurong", "Bukit Batok", "Clementi", "Choa Chu Kang", "Boon Lay"],
        },
    },
    "IN": {
        "states":   [
            "Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "Uttar Pradesh",
            "West Bengal", "Gujarat", "Rajasthan", "Madhya Pradesh",
            "Andhra Pradesh",
        ],
        "networks": ["Jio", "Airtel", "Vi", "BSNL", "MTNL"],
        "cities": {
            "Maharashtra":   ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane"],
            "Delhi":         ["New Delhi", "Delhi", "Noida", "Gurgaon", "Faridabad"],
            "Karnataka":     ["Bengaluru", "Mysuru", "Mangaluru", "Hubli", "Belagavi"],
            "Tamil Nadu":    ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
            "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Meerut", "Ghaziabad"],
            "West Bengal":   ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"],
            "Gujarat":       ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
            "Rajasthan":     ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer"],
            "Madhya Pradesh":["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"],
            "Andhra Pradesh":["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati"],
        },
    },
    "BR": {
        "states":   [
            "Sao Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Parana",
            "Rio Grande do Sul", "Pernambuco", "Ceara", "Para", "Maranhao",
        ],
        "networks": ["Claro", "Vivo", "TIM", "Oi", "Nextel"],
        "cities": {
            "Sao Paulo":       ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André"],
            "Rio de Janeiro":  ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói"],
            "Minas Gerais":    ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Montes Claros"],
            "Bahia":           ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna"],
            "Parana":          ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel"],
            "Rio Grande do Sul":["Porto Alegre", "Caxias do Sul", "Canoas", "Pelotas", "Santa Maria"],
            "Pernambuco":      ["Recife", "Caruaru", "Petrolina", "Olinda", "Paulista"],
            "Ceara":           ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral"],
            "Para":            ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal"],
            "Maranhao":        ["São Luís", "Imperatriz", "São José de Ribamar", "Timon", "Caxias"],
        },
    },
}